<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE telecom_service_provider [
	<!ELEMENT telecom_service_provider (program_list, combinational_program_offer_list)>
	<!ELEMENT program_list (program)+>
	<!ELEMENT combinational_program_offer_list (combinational_program_offer)*>
	<!ELEMENT program (program_name, secondary_mobile_categ?, secondary_home_teleph_and_internet_categ?,
	program_services_package, contract_commitment,(new_sim|new_router|new_decoder)?, benefits_list, prices_list, additional_charges_list?)>
	<!ELEMENT program_name (#PCDATA)>
	<!ELEMENT secondary_mobile_categ EMPTY>
	<!ELEMENT secondary_home_teleph_and_internet_categ EMPTY>
	<!ELEMENT program_services_package (data?, mobile_calls_same?, home_calls_same?, home_national_calls_a?,
	home_national_calls?, mobile_national_calls?, remaining?, international_calls?, sms_same?, sms_national?, sms_international?,
	TV_channels?, speed?)>
	<!--<!ELEMENT program_services_package_mobile (data?, mobile_calls_same?, home_calls_same?, home_national_calls_a?, remaining?, international_calls?, sms_same?,  )-->
	<!ELEMENT contract_commitment (#PCDATA)>

	<!--<!ELEMENT new_sim -->

	<!ELEMENT new_router (#PCDATA)>
	<!ELEMENT new_decoder (#PCDATA)>
	<!ELEMENT data (#PCDATA)>
	<!ELEMENT mobile_calls_same (#PCDATA)>
	<!ELEMENT home_calls_same (#PCDATA)>
	<!ELEMENT home_national_calls (#PCDATA)>
	<!ELEMENT mobile_national_calls (#PCDATA)>
	<!ELEMENT remaining (#PCDATA)>
	<!ELEMENT sms_same (#PCDATA)>
	<!ELEMENT sms_national (#PCDATA)>
	<!ELEMENT sms_international (#PCDATA)> 
	<!ELEMENT international_calls (#PCDATA| counties)*>
	<!ELEMENT TV_channels EMPTY>
	<!ELEMENT benefits_list (benefits)*>
	<!ELEMENT additional_charges_list (activation_fees?, installation_fees?)>

	<!ELEMENT prices_list (new_client_prices?, old_client_prices?, company_prices?)>
	
	<!ELEMENT speed (#PCDATA)>
	<!ELEMENT countries (country_name)>
	<!ELEMENT country_name (#PCDATA)>
	<!ELEMENT activation_fees (#PCDATA)>
	<!ELEMENT installation_fees (#PCDATA)>
	<!ELEMENT new_client_prices (#PCDATA)>
	<!ELEMENT old_client_prices (#PCDATA)>
	<!ELEMENT company_prices (#PCDATA)>
	<!ELEMENT offers_list (program+, offer*)>
	<!ELEMENT offer (validity_period, contract_commitment, bonus*)>
	<!ELEMENT validity_period EMPTY>
	<!ELEMENT bonus (#PCDATA)>


	<!ATTLIST telecom_service_provider brand_name CDATA #REQUIRED>
	<!ATTLIST telecom_service_provider establishment_year CDATA #REQUIRED>
	<!ATTLIST program code ID #REQUIRED>
	<!ATTLIST program_name category (mobile|home_teleph_and_internet|TV) "mobile">

<!--	<!ATTLIST program_name IDREF                    #REQUIRED> -->

	<!ATTLIST secondary_mobile_categ value_info_m (contract|card_program|prepaid) #REQUIRED>
	<!ATTLIST secondary_home_teleph_and_internet_categ value_info_h (GigaFiber|VDSL|ADSL) #REQUIRED>
	<!ATTLIST countries consumption (mobile|home|home_and_mobile) "home" #REQUIRED>
<!--<!ATTLIST new_sim provides_new_sim (yes|no) "no" -->
	<!ATTLIST new_router router_model #REQUIRED>
	<!ATTLIST new_decoder decoder_model #REQUIRED>
    <!ATTLIST TV_channels channel_number (yes|no) #REQUIRED>
	<!ATTLIST TV_channels kids_program (yes|no) #REQUIRED>
	<!ATTLIST TV_channels sports (yes|no) #REQUIRED>
	<!ATTLIST TV_channels filmcase (yes|no) "no" #REQUIRED>
	<!ATTLIST benefits_list benefits_number #REQUIRED>
	<!ATTLIST new_client_prices new_client #REQUIRED>
	<!ATTLIST old_client_prices old_client #REQUIRED>
	<!ATTLIST company_prices company #REQUIRED>

	<!ATTLIST offer offer_program_code IDREF #REQUIRED>
	<!ATTLIST offer offer_price CDATA #REQUIRED>
	<!ATTLIST offer VAT_price CDATA #REQUIRED>
	<!ATTLIST offer client (new_client|old_client|company) #REQUIRED>
	<!ATTLIST validity_period from CDATA #REQUIRED>
	<!ATTLIST validity_period to CDATA #REQUIRED>
	<!ATTLIST bonus bonus_category CDATA #IMPLIED>

]>
<telecom_service_provider>
	<program_list>
		<program code="A1"> 
			<program_name category="mobile">
				Mobile Start 1
			</program_name>
			<secondary_mobile_categ value_info_m="contract"/>
			<program_services_package>
				<data>
					2500
				</data>
				<mobile_calls_same>
					750
				</mobile_calls_same>
				<home_calls_same>
					150
				</home_calls_same>
				<home_national_calls_a>
					100
				</home_national_calls_a>
				<international_calls>
					50
					<countries consumption="mobile">
						<country_name>
							England
						</country_name>
					</counties>
				</international_calls>
				<sms_same>
					80
				</sms_same>
				<sms_national>
					20
				</sms_national>
				<sms_international>
					10
				</sms_international>	
			</program_services_package>
			<contract_commitment>
				24 months
			</contract_commitment>
			<new_sim>

			</new_sim>
		</program>

		<program code="A2">
			<program_name category="home_teleph_and_internet">
				home Start 1
			</program_name>
			<secondary_home_teleph_and_internet_categ value_info_h "GigaFiber"/>
			<home_national_calls_a>
				100
			</home_national_calls_a>
			<international_calls>
				50
				<countries consumption="mobile">
					<country_name>
						England
					</country_name>
				</countries>
			</international_calls>
			<contract_commitment>
				24 months
			</contract_commitment>	
			<new_router>
			</new_router>
		</program>

	</program_list>




































</telecom_service_provider>
